### ISSUE TITLE
Proba

### ISSUE THREAD

**Issue by teosarkic** [PetljaIT/bugs-and-improvements#1]
Public je

**Comment by igr** [comment]
Da li je ovaj repo aktuelan?

**Comment by teosarkic** [comment]
@igr ovaj repo nije aktuelan, mislim da nikad zapravo nije zaziveo, da je bio samo u fazi probe :)
Jesi li naleteo na njega pretragom po GitHub-u ili je negde ulinkovan na Petlja.org?

**Comment by igr** [comment]
samo pretragom.

**Comment by teosarkic** [comment]
Hvala! Zatvram ovaj repo da ne zbunjuje ljude :)
